apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mine-saker-api
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: mine-saker-api-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /mine-saker-api/internal/isAlive
    initialDelay: 15
  readiness:
    path: /mine-saker-api/internal/isReady
    initialDelay: 15
  prometheus:
    enabled: true
    path: /mine-saker-api/metrics
  secureLogs:
    enabled: true
  replicas:
    min: 2
    max: 4
  webproxy: true
  idporten:
    enabled: true
    postLogoutRedirectURIs:
      - "https://www.nav.no"
    sidecar:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dittnav-api
    outbound:
      external:
        - host: "https://safselvbetjening.prod-fss-pub.nais.io"
        - host: "https://sosialhjelp-soknad-api.prod-fss-pub.nais.io"
        - host: "https://sosialhjelp-soknad-api.nais.oera.no"
      rules:
        - application: "safselvbetjening"
          namespace: "teamdokumenthandtering"
          cluster: "prod-fss"
  ingresses:
    - "https://person.nav.no/mine-saker-api"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 580Mi
  env:
    - name: DAGPENGER_INNSYN
      value: https://www.nav.no/arbeid/dagpenger/mine-dagpenger
    - name: HJELPEMIDLER_INNSYN
      value: https://www.nav.no/hjelpemidler/dinehjelpemidler
    - name: SOSIALHJELP_INNSYN
      value: https://www.nav.no/sosialhjelp/innsyn
    - name: AAP_INNSYN
      value: https://www.nav.no/aap/mine-aap
    - name: SYKEFRAVAER_INNSYN
      value: https://www.nav.no/syk/sykefravaer
    - name: DEFAULT_INNSYN_LENKE
      value: https://person.nav.no/mine-saker/tema
