apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mine-saker-api
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /mine-saker-api/internal/isAlive
    initialDelay: 15
  readiness:
    path: /mine-saker-api/internal/isReady
    initialDelay: 15
  redis:
    - instance: fullmakt
      access: readwrite
  prometheus:
    enabled: true
    path: /mine-saker-api/metrics
  secureLogs:
    enabled: true
  replicas:
    min: 2
    max: 4
  webproxy: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: idporten-loa-substantial
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: "safselvbetjening.prod-fss-pub.nais.io"
        - host: "sosialhjelp-soknad-api.prod-fss-pub.nais.io"
        - host: "sosialhjelp-soknad-api.nais.oera.no"
        - host: "pdl-fullmakt.prod-fss-pub.nais.io"
        - host: "pdl-api.prod-fss-pub.nais.io"
      rules:
        - application: "safselvbetjening"
          namespace: "teamdokumenthandtering"
          cluster: "prod-fss"
  ingresses:
    - "https://person.nav.no/mine-saker-api"
  resources:
    limits:
      memory: 768Mi
    requests:
      memory: 580Mi
  env:
    - name: SOSIALHJELP_INNSYN
      value: https://www.nav.no/sosialhjelp/innsyn
    - name: DEFAULT_INNSYN_LENKE
      value: https://person.nav.no/dokumentarkiv/tema
    - name: CORS_ALLOWED_ORIGINS
      value: "*.nav.no"
    - name: DIGISOS_API_URL
      value: https://sosialhjelp-soknad-api.prod-fss-pub.nais.io/sosialhjelp/soknad-api
    - name: DIGISOS_CLIENT_ID
      value: prod-fss:teamdigisos:sosialhjelp-soknad-api
    - name: SAF_API_URL
      value: https://safselvbetjening.prod-fss-pub.nais.io
    - name: SAF_CLIENT_ID
      value: prod-fss:teamdokumenthandtering:safselvbetjening
    - name: MINE_SAKER_URL
      value: https://person.nav.no/dokumentarkiv
    - name: PDL_FULLMAKT_URL
      value: "https://pdl-fullmakt.prod-fss-pub.nais.io"
    - name: PDL_FULLMAKT_CLIENT_ID
      value: "prod-fss:pdl:pdl-fullmakt"
    - name: PDL_API_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: PDL_API_CLIENT_ID
      value: "prod-fss:pdl:pdl-api"
    - name: PDL_BEHANDLINGSNUMMER
      value: "B499"
