apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mine-saker-api
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /mine-saker-api/internal/isAlive
    initialDelay: 15
  readiness:
    path: /mine-saker-api/internal/isReady
    initialDelay: 15
  valkey:
    - instance: fullmakt
      access: readwrite
  prometheus:
    enabled: true
    path: /mine-saker-api/metrics
  secureLogs:
    enabled: true
  replicas:
    min: 2
    max: 4
  webproxy: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: idporten-loa-substantial
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: "safselvbetjening.dev-fss-pub.nais.io"
        - host: "pdl-fullmakt.dev-fss-pub.nais.io"
        - host: "pdl-api.dev-fss-pub.nais.io"
      rules:
        - application: "safselvbetjening"
          namespace: "teamdokumenthandtering"
          cluster: "dev-fss"
        - application: "repr-api"
          namespace: "repr"
        - application: "sosialhjelp-soknad-api"
          namespace: "teamdigisos"
    inbound:
      rules:
        - application: "tms-min-side"
        - application: "tms-dokumentarkiv"
  ingresses:
    - "https://www.intern.dev.nav.no/mine-saker-api"
    - "https://www.ansatt.dev.nav.no/mine-saker-api"
  resources:
    limits:
      cpu: "1"
      memory: 1280Mi
    requests:
      cpu: "20m"
      memory: 256Mi
  env:
    - name: CORS_ALLOWED_ORIGINS
      value: "*.dev.nav.no"
    - name: SAF_API_URL
      value: https://safselvbetjening.dev-fss-pub.nais.io
    - name: SAF_CLIENT_ID
      value: dev-fss:teamdokumenthandtering:safselvbetjening
    - name: MINE_SAKER_URL
      value: https://www.intern.dev.nav.no/dokumentarkiv/
    - name: REPR_FULLMAKT_URL
      value: "http://repr-api.repr"
    - name: REPR_FULLMAKT_CLIENT_ID
      value: "dev-gcp:repr:repr-api"
    - name: PDL_API_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_API_CLIENT_ID
      value: "dev-fss:pdl:pdl-api"
    - name: PDL_BEHANDLINGSNUMMER
      value: "B499"
    - name: DIGISOS_API_URL
      value: http://sosialhjelp-soknad-api.teamdigisos/sosialhjelp/soknad-api
    - name: DIGISOS_CLIENT_ID
      value: dev-gcp:teamdigisos:sosialhjelp-soknad-api
