apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mine-saker-api
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: mine-saker-api-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /mine-saker-api/internal/isAlive
    initialDelay: 15
  readiness:
    path: /mine-saker-api/internal/isReady
    initialDelay: 15
  prometheus:
    enabled: true
    path: /mine-saker-api/metrics
  replicas:
    min: 2
    max: 4
  webproxy: true
  idporten:
    enabled: true
    postLogoutRedirectURIs:
      - "https://www.dev.nav.no"
    sidecar:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dittnav-api
    outbound:
      external:
        - host: "safselvbetjening-q1.dev-fss-pub.nais.io"
        - host: "sosialhjelp-soknad-api-intern.dev.nav.no"
        - host: "sosialhjelp-soknad-api.dev-fss-pub.nais.io"
      rules:
        - application: "safselvbetjening-q1"
          namespace: "teamdokumenthandtering"
          cluster: "dev-fss"
  ingresses:
    - "https://person.dev.nav.no/mine-saker-api"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 580Mi
